### ISSUE TITLE
Training large datasets (umap issue?)

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/zaira-chem#1]
When I 'zairachem fit' larger datasets, I get a crash after descriptor calculation as in the log file attached. So far anything above 7000 data points is too much and under 4000 is fine.

The crash seems to occur within the save function of the umap class and I remember you mentioning there was an issue with umap and larger datasets? 

I've confirmed that it is not a data issue as I get passed this step when training on each half of the same data separately.

[Chembl_inhibition_7000.txt](https://github.com/ersilia-os/zaira-chem/files/8445871/Chembl_inhibition_7000.txt)

**Comment by GemmaTuron** [comment]
Hi @JHlozek and @miquelduranfrigola

Some more info on this error:
- There is an incompatibility between cloudpickle and dill packages. Joblib is trying to use dill to save the UMAP because it is too large
- It specifically crashes when saving umap.json

A solution proposer by @miquelduranfrigola previously would be to do a PCA before the UMAP step

**Comment by miquelduranfrigola** [comment]
Hi @JHlozek and @GemmaTuron now the umap class does PCA before. I trust this will solve the issue. Please try and let me know.

**Comment by JHlozek** [comment]
@miquelduranfrigola 

I can confirm that the issue is solved. :)

**Comment by JHlozek** [comment]
@miquelduranfrigola Unfortunately the problem doesn't seem resolved. I didn't let the original test run long enough so it wasn't actually resolved in the first place (apologies for the confusion).

Here is a data set that crashes with the corresponding log:
[Chembl_A_baumannii_inhibition_train_log.txt](https://github.com/ersilia-os/zaira-chem/files/8471895/Chembl_A_baumannii_inhibition_train_log.txt)
[Chembl_A_baumannii_inhibition_train.csv](https://github.com/ersilia-os/zaira-chem/files/8471897/Chembl_A_baumannii_inhibition_train.csv)
.

**Comment by GemmaTuron** [comment]
Hi, I have some additional info, as it seems reducing the dimensions will not help in this issue.
We should limit dill's functionality to prevent issues with cloudpickle (see https://github.com/SeldonIO/alibi/issues/447) or https://github.com/dmlc/xgboost/issues/6239) or perhaps adding these dill settings: https://github.com/uqfoundation/dill/issues/383#issuecomment-682144392

**Comment by miquelduranfrigola** [comment]
Hi all. I have decided to keep a maximum of 1,000 molecules at fitting time for the UMAP. This is fine, I believe, especially because UMAP is only a small step of ZairaChem. This solution works in my computer.

It seems that upgrading requirements to Python 3.8 would solve the `dill` issue, so I may explore this option in the future (not a priority atm).
