### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by sistar2020** [ersilia-os/zaira-chem#25]
**Describe the bug**
Installation failure.

**To Reproduce**
```
1. wget https://github.com/ersilia-os/zaira-chem/archive/refs/tags/v1.0.0.tar.gz
2. tar zxf v1.0.0.tar.gz
3. cd zaira-chem-1.0.0
4. sh install_linux.sh
```

**Errors**
```
.....
Installing collected packages: imbalanced-learn
Successfully installed imbalanced-learn-0.10.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///opt/modeling/qsar/zaira-chem
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in zairachem setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
          version https://git-lfs.github.com/spec/v1
                  ^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by sistar2020** [comment]
But installation proceeded fine if I pull the code using "git":
```
$ git clone https://github.com/ersilia-os/zaira-chem.git
$ cd zaira-chem
$ sh install_linux.sh
```
To use nvidia graphics card, I also had to install dgl-cuda.
`$ conda install --offline dgl-cuda10.1-0.9.1-py37_0.tar.bz2`

Above steps worked ok.

**Comment by gdreiman-insitro** [comment]
I'm having a similar issue, except pulling with `git clone` doesn't solve the problem. Any suggestions?

**Comment by gdreiman-insitro** [comment]
Finally sorted this out. In short, this repo assumes that you have `git-lfs` installed, I didn't. If you run into this, install `git-lfs` and then `rm -rf` the repo. When you `git clone` it again, the `requirements.txt` file will be retrieved from git lfs and you can install the environment properly. 

A note to the authors, it might not make sense to store such a small file with lfs. Providing it directly would simplify install, especially since many Amazon EC2 AMIs don't have `git-lfs` by default and unpacking the current `requirements.txt` file gives very confusing errors.

**Comment by GemmaTuron** [comment]
Hi @gdreiman-insitro 

Thansk for the insight. The reason Git-LFS is required is because the Ersilia Model Hub does require Git-lfs (though we are removing that dependency by moving to S3 buckets and/or Docker containers). In any case we can revise the Git LFS requirements for the ZairaChem repository itself to avoid confusions - thanks

**Comment by GemmaTuron** [comment]
The Git-LFS dependency has been resolved, I'll close this issue
